pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=github-actions[bot]
      - check-success=build-linux
      - base=refs/heads/develop
    actions:
      merge:
        method: merge
