description = "Ubuntu bionic base image with buildpacks for Java, .NET Core, NodeJS, Go, Python, PHP, Ruby, Apache HTTPD, NGINX and Procfile"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/dotnet-core:0.9.0"
  version = "0.9.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/go:0.12.0"
  version = "0.12.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/httpd:0.2.0"
  version = "0.2.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java-native-image:5.12.0"
  version = "5.12.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java:5.21.1"
  version = "5.21.1"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nginx:0.5.2"
  version = "0.5.2"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nodejs:0.11.1"
  version = "0.11.1"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/php:0.6.1"
  version = "0.6.1"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.0.0"
  version = "5.0.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/python:0.9.0"
  version = "0.9.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/ruby:0.9.1"
  version = "0.9.1"

[[buildpacks]]
  id = "koyeb/custom"
  uri = "docker://koyeb/custom-buildpack"

[[buildpacks]]
  id = "heroku/clojure"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/clojure?version=0.0.0&name=Clojure"

[lifecycle]
  version = "0.15.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ruby"
    version = "0.9.1"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core"
    version = "0.9.0"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "0.11.1"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go"
    version = "0.12.0"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/python"
    version = "0.9.0"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/php"
    version = "0.6.1"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "0.5.2"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.2.0"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "5.12.0"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "5.21.1"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.0.0"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/clojure"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.2"
    optional = true

[stack]
  build-image = "koyeb/pack:1.3.0-full-cnb"
  id = "io.buildpacks.stacks.bionic"
  run-image = "koyeb/pack:full-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:full-cnb"]
