description = "Base builder for Heroku-20 stack, based on ubuntu:20.04 base image"

[stack]
  id = "heroku-20"
  build-image = "koyeb/pack:20-cnb-build"
  run-image = "koyeb/pack:20-cnb"

[lifecycle]
  version = "0.15.3"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:7e4a2bc5f80e6892949117e3ae48ecac0b54760058999c48a5907a56268949fe"

[[buildpacks]]
  id = "heroku/scala"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/scala?version=0.0.0&name=Scala"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/gradle?version=0.0.0&name=Gradle"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/ruby?version=0.0.0&name=Ruby"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb@sha256:ea7219d4bb50196b4f292c9aae397b17255c59a243d7408535d2a03a5cd2b040"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.0.0&name=Python"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.0.0&name=PHP"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.0.0&name=Go"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:94a5360759d28b86415a5c8e7f4602591154b97d51573eb3d353d84397c35602"

[[buildpacks]]
  id = "heroku/clojure"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/clojure?version=0.0.0&name=Clojure"

[[buildpacks]]
  id = "koyeb/custom"
  uri = "docker://koyeb/buildpack-custom"

[[buildpacks]]
  id = "koyeb/custom-nodejs"
  uri = "docker://koyeb/buildpack-custom-nodejs"

[[order]]

  [[order.group]]
    id = "heroku/ruby"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/python"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/scala"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/php"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/go"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "koyeb/custom-nodejs"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "heroku/nodejs"
    version = "1.1.4"

[[order]]

  [[order.group]]
    id = "heroku/java"
    version = "3.0.0"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/jvm"
    version = "3.0.0"

  [[order.group]]
    id = "heroku/gradle"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/clojure"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true
