description = "Base builder for Heroku-18 stack, based on ubuntu:18.04 base image"

[stack]
  id = "heroku-18"
  build-image = "koyeb/pack:18-cnb-build"
  run-image = "koyeb/pack:18-cnb"

[lifecycle]
  version = "0.14.1"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-buildpack@sha256:cb4757bcaf4da69d45931b164297dd32e39bdac0636a5ab1be01b0a502b6457f"

[[buildpacks]]
  id = "heroku/scala"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/scala?version=0.0.0&name=Scala"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-function-buildpack@sha256:f0b285a99116ab20a0cdb9c6c4f60dcd98867cf4be2c416813d13148d0bdaf15"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/gradle?version=0.0.0&name=Gradle"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-ruby-buildpack@sha256:3eeb3773cdbd29d4fb0d578f7781fe8c525de73593480e2740b7143262e5bef5"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:1.0.2"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.0.0&name=Python"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.0.0&name=PHP"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.0.0&name=Go"

[[buildpacks]]
  id = "koyeb/nodejs"
  uri = "docker://koyeb/nodejs-buildpack@sha256:61a9bdc0c1a9ccbb8dd466f9acd4e68597a3acbaed1153215c05b5f4a66fb0a4"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-buildpack@sha256:e3e79d976328e0967fb10b4fe95aabc433ae7d4b9d0ab0ef457454c399aaf235"

[[buildpacks]]
  id = "koyeb/custom"
  uri = "docker://koyeb/buildpack-custom"

[[buildpacks]]
  id = "koyeb/custom-nodejs"
  uri = "docker://koyeb/buildpack-custom-nodejs"

[[order]]

  [[order.group]]
    id = "heroku/ruby"
    version = "0.1.3"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/python"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/scala"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/php"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/go"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/nodejs-function"
    version = "0.9.8"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.34"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "koyeb/custom-nodejs"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "koyeb/nodejs"
    version = "0.5.1"

[[order]]

  [[order.group]]
    id = "heroku/java"
    version = "0.6.2"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/jvm"
    version = "1.0.2"

  [[order.group]]
    id = "heroku/gradle"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true
