description = "Koyeb buildpack based on heroku buildpack"

[stack]
  id = "heroku-22"
  build-image = "koyeb/pack:22-cnb-build"
  run-image = "koyeb/pack:22-cnb"

[lifecycle]
  version = "0.15.3"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:ab0e16dbcec105af6173f8422a190b48fe6b89a324e5e7f027ec4d5eb432d3de"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:20b9b71a87e94e82d2e3a54e9329af49bce93d61211e4169cfe7b490972cf8d0"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:adeffc67d226f1d36c9ac0766a189a34efbfe3bd62c1bc07aa9a24c785fe4f70"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:9d76792ba9869eb96ba3b41b0bfb48c6adfaa58a361bba6083505c84c5a8d61e"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb@sha256:2549eee29b64c5dc063a3966c65baf1f264389645f54d416a320aa9e20b09592"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:86561a5b5ed7ea378068c0adb30d117239f5cee2c521fdece8a05430b479ec1b"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:b82d0a0d59dd97615fe082e4e31c3af25790dd88a0c5c6b8d553504f6b22526b"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:dcf51d14112e5b97cf2f7e1cd19dd89e4850762080dc29c80623c02413ca6e6f"

[[buildpacks]]
  id = "heroku/clojure"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/clojure?version=0.0.0&name=Clojure"

[[buildpacks]]
  id = "koyeb/custom"
  uri = "docker://koyeb/buildpack-custom"

[[buildpacks]]
  id = "koyeb/custom-nodejs"
  uri = "docker://koyeb/buildpack-custom-nodejs"

[[order]]

  [[order.group]]
    id = "heroku/python"
    version = "0.8.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "2.6.5"
    optional = true

  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "2.6.5"
    optional = true

  [[order.group]]
    id = "heroku/jvm"
    version = "4.1.0"
    optional = true

  [[order.group]]
    id = "heroku/ruby"
    version = "2.1.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "koyeb/custom-nodejs"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "heroku/nodejs"
    version = "2.6.5"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/java"
    version = "4.1.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/scala"
    version = "4.1.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/go"
    version = "0.1.14"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/php"
    version = "0.1.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/clojure"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true
