description = "Koyeb buildpack based on heroku buildpack"

[stack]
  id = "heroku-22"
  build-image = "koyeb/pack:22-cnb-build"
  run-image = "koyeb/pack:22-cnb"

[lifecycle]
  version = "0.15.3"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:794bf260eddfbcac0724edd8b5b7dab17aa52070f9f680d8da18ad3845228667"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:7215ec11a198f04da57355043ef9e61a5af699fb96c8a320e22df1832ba275b4"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:ecc7167d15d443b2f8cc61350999332b78c1177cbc702d5bae646fd3736d6f72"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:9d76792ba9869eb96ba3b41b0bfb48c6adfaa58a361bba6083505c84c5a8d61e"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb@sha256:2549eee29b64c5dc063a3966c65baf1f264389645f54d416a320aa9e20b09592"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:5785d433616f0b72d7ceb576896d5e288fe59b7271169fa09feee3d0cd448444"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:b82d0a0d59dd97615fe082e4e31c3af25790dd88a0c5c6b8d553504f6b22526b"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:f5c6608a0f81058872eabe4d4829e80650d7388a59b6c3bf866d38ab7111eabe"

[[buildpacks]]
  id = "heroku/clojure"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/clojure?version=0.0.0&name=Clojure"

[[buildpacks]]
  id = "koyeb/custom"
  uri = "docker://koyeb/buildpack-custom"

[[buildpacks]]
  id = "koyeb/custom-nodejs"
  uri = "docker://koyeb/buildpack-custom-nodejs"

[[order]]

  [[order.group]]
    id = "heroku/python"
    version = "0.8.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "2.6.2"
    optional = true

  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "2.6.2"
    optional = true

  [[order.group]]
    id = "heroku/jvm"
    version = "4.0.2"
    optional = true

  [[order.group]]
    id = "heroku/ruby"
    version = "2.1.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "koyeb/custom-nodejs"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "heroku/nodejs"
    version = "2.6.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/java"
    version = "4.0.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/scala"
    version = "4.0.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/go"
    version = "0.1.13"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/php"
    version = "0.1.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/clojure"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.2"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true
