name: E2E tests

on:
  schedule:
    - cron: "9 10 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo: [example-nextjs]
        include:
          - repo: example-nextjs
            port: 3000
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.KOYEB_STAGING_API_TOKEN }}"
          api_url: "${{ secrets.KOYEB_API_URL }}"

      - name: "Build ${{matrix.repo}}"
        uses: koyeb/action-git-deploy@v1
        with:
          git-url: "github.com/koyeb/${{matrix.repo}}"
          git-branch: main
          app-name: "${{ matrix.repo }}-${{ github.ref_name }}"
          service-ports: "${{matrix.port}}:http"
          service-routes: "/:${{matrix.port}}"

      - name: "Cleanup ${{matrix.repo}}"
        uses: koyeb/action-git-deploy/cleanup@v1
        with:
          app-name: '${{matrix.repo}}-${{ github.head_ref }}'
