name: generate

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          ref: refs/heads/develop
      - name: install yj
        run: |
          echo "Installing yj to /usr/local/bin"
          wget https://github.com/sclevine/yj/releases/download/v5.0.0/yj-linux -O /usr/local/bin/yj
          chmod a+x /usr/local/bin/yj
      - name: Checkout heroku buildpacks
        uses: actions/checkout@v2
        with:
          repository: heroku/cnb-builder-images
          path: .source/heroku
      - name: copy
        run: |
          cp .source/heroku/buildpacks-20/builder.toml builders/heroku/20/builder.toml
          cp .source/heroku/builder-22/builder.toml builders/heroku/22/builder.toml
      - name: patch
        run: |
          make patch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          body: |
            Auto-generated by [create-pull-request]
